INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/platform/CommonFlags.cmake)

IF( (${TARGET_PLATFORM} STREQUAL "CYT2B75_M0PLUS") OR (${TARGET_PLATFORM} STREQUAL "CYT2B75_M4") )
    INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/platform/cyt2b75/FindFlags.cmake)
ELSEIF(${TARGET_PLATFORM} STREQUAL "C2000")
    INCLUDE(${CMAKE_CURRENT_SOURCE_DIR}/platform/c2000/FindFlags.cmake)
ENDIF()
